perf(test): improve timeout for test cases
eicrud/eicrud pull request #101
Opened 2024-11-11 16:51 UTC by shreyas4510

Timeout values added for test cases from environment variables.

Fixes issue #100.

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/eicrud/eicrud/blob/develop/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (optional)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?
- [ ] Yes
- [ ] No

## Other information

2024-11-11 17:24 UTC, acrosett requested changes
added a few more comments,

ideally we could make use of the `setup.js` mentioned in this [issue](https://stackoverflow.com/questions/58042401/configure-jest-timeout-once-for-all-tests) so that we can set the default timeout for all tests and ditch the `"testTimeout"` in `package.json`. However we can already merge this if you want

2024-11-11 17:24 UTC, acrosett commented on .github/workflows/action-publish.yml
this seems to be in the wrong place, here it is attached to the mongo service

2024-11-11 17:24 UTC, acrosett commented on .github/workflows/action-test.yml
same here

2024-11-11 17:24 UTC, acrosett commented on test/core/core.account.spec.ts
some tests that were 7000 are now 6000 with the new default, it can break the CI if these are lowered

2024-11-12 12:20 UTC, acrosett requested changes

2024-11-12 12:20 UTC, acrosett commented on test/src/app.module.ts
small typo here, `postgresPasword` should be `postgresPassword`

2024-11-12 12:20 UTC, acrosett commented on package.json
we need to keep this, the default timeout for tests is 5000 so if you remove this it will reduce and might break the CI

2024-11-12 12:32 UTC, shreyas4510 commented on package.json
No I have updated default to 8000 in env.ts file so when no env variable which will be true in case of CI then it will take 8000

2024-11-12 12:36 UTC, acrosett commented on package.json
my bad, didn't see the `jest.setTimeout(timeout);`, all good

2024-11-12 12:40 UTC, acrosett approved these changes

2024-11-12 14:00 UTC, merged